### ISSUE TITLE
Package "sva" is not available from CRAN

### ISSUE THREAD

**Issue by hendrikweisser** [broadinstitute/prism_data_processing#2]
In "requirements.R", `install.packages` is called for package "sva":
https://github.com/broadinstitute/prism_data_processing/blob/master/requirements.R#L9

"sva" is a Bioconductor package (https://bioconductor.org/packages/release/bioc/html/sva.html) and cannot be installed in that way.

**Comment by aboghossian** [comment]
Should be fixed now
