### ISSUE TITLE
Unclear relationship between CCLE data and PRISM inputs

### ISSUE THREAD

**Issue by hendrikweisser** [broadinstitute/prism_data_processing#3]
According to the README, the `MTS_Analysis.R` script:
> Requires a directory of expression data (RNA, mutations, etc.)

And:
> Public cell line data for equivalent analysis is available on the [DepMap Portal](https://depmap.org/portal/).

The corresponding code is here:
https://github.com/broadinstitute/prism_data_processing/blob/master/MTS_Analysis.R#L11-L29
And here:
https://github.com/broadinstitute/prism_data_processing/blob/master/MTS_Analysis.R#L37-L45

Unfortunately it is not entirely clear how the input files mentioned in the code relate to the CCLE data files from DepMap (available here: https://depmap.org/portal/download/all/). In particular, for some data types multiple files are available in DepMap.

To enable use of the code in this repository, it would be great if the following questions could be answered:
- Which DepMap file corresponds to which PRISM input file?
- Is any preprocessing of the DepMap files required?
- How have the "x-all.csv" and "x-ccle.csv" files been generated?

**Comment by aboghossian** [comment]
Thanks for the feedback, the README now has some information about which files to download and there is a script for processing them into the right format (matrix)
