### ISSUE TITLE
rep_info (repurposing metadata) missing from scripts

### ISSUE THREAD

**Issue by tylerhill90** [broadinstitute/prism_data_processing#5]
**Describe the bug**
The file "rep_info.csv" is referenced in MTS_Analysis.R but there is no reference to it in the README.
In src/biomarker_tables.R there is a call on line 144 to the variable "rep_info" with no previous assignment.
"rep_info.csv" is also not saved to .csv in src/biomarker_tables.R for later use in the MTS_Analysis.R script.

I have been working with the primary-screen-replicate-collapsed-treatment-info.csv file from DepMap as the source for rep_info (repurposing metadata) but it is not mentioned in the **NOTE:** under the MTS_Analysis.R section in the README.

Cheers for all the hard work at the Broad!

**Comment by aboghossian** [comment]
Thanks for catching this! It is supposed to refer to the `primary-screen-replicate-collapsed-treatment-info` file which can be downloaded from the portal. I will add that to the readme and make sure the code is updated

**Comment by tylerhill90** [comment]
Hello again. I was wondering if the proteomics file you have listed in the README is correct as we are running into some confusing results when comparing our biomarker analysis results to the results given to us by the Broad. Specifically, the Broad's analysis contains 1000 ranks whereas the proteomics file listed (CCLE_RPPA_20181003.csv) only has 214 antibodies.

We were also curious about which release of the CCLE data we should use to more accurately reflect the data processing and analysis results given to us from the Broad for internal screens.

Thanks again for any clarification.

**Comment by aboghossian** [comment]
We transitioned from the RPPA dataset to the protein_quant_current_normalized version. Sorry for any confusion about this repo it has fallen out of date but I am working to get our public code back up to speed (so I appreciate you pointing out discrepancies). The hope is to have updated code and docker images soon.

The CCLE data that will most accurately reflect your internal data will be the release that was the latest at the time of data processing
